package dev.gavenda.yuuka.ui.theme

import androidx.compose.ui.graphics.Color

// Material 3 medium-contrast scheme generated from the brand seed #4C5CDC.
// Used when dynamic colour is off or unavailable; regenerate the whole set from a new
// seed rather than editing single roles. The web app mirrors it in `webapp/src/style.css`;
// change them together.

val LightPrimary = Color(0xFF182AB0)
val LightOnPrimary = Color(0xFFCDD1FF)
val LightPrimaryContainer = Color(0xFF5767E7)
val LightOnPrimaryContainer = Color(0xFFFFFFFF)
val LightSecondary = Color(0xFF3B2D97)
val LightOnSecondary = Color(0xFFD5CFFF)
val LightSecondaryContainer = Color(0xFF7166D0)
val LightOnSecondaryContainer = Color(0xFFFFFFFF)
val LightTertiary = Color(0xFF71185E)
val LightOnTertiary = Color(0xFFFFC2E8)
val LightTertiaryContainer = Color(0xFFB25197)
val LightOnTertiaryContainer = Color(0xFFFFFFFF)
val LightError = Color(0xFF83002A)
val LightOnError = Color(0xFFFFC6CA)
val LightErrorContainer = Color(0xFFD73357)
val LightOnErrorContainer = Color(0xFFFFFFFF)
val LightSurface = Color(0xFFF9F5FF)
val LightBackground = Color(0xFFF9F5FF)
val LightOnSurface = Color(0xFF1E1A40)
val LightSurfaceVariant = Color(0xFFDED8FF)
val LightOnSurfaceVariant = Color(0xFF3E3A62)
val LightSurfaceDim = Color(0xFFD5CFFF)
val LightSurfaceBright = Color(0xFFF9F5FF)
val LightSurfaceContainerLowest = Color(0xFFFFFFFF)
val LightSurfaceContainerLow = Color(0xFFF3EEFF)
val LightSurfaceContainer = Color(0xFFEAE5FF)
val LightSurfaceContainerHigh = Color(0xFFE4DFFF)
val LightSurfaceContainerHighest = Color(0xFFDED8FF)
val LightOutline = Color(0xFF5B5780)
val LightOutlineVariant = Color(0xFF7670AB)
val LightInverseSurface = Color(0xFF0D072E)
val LightInverseOnSurface = Color(0xFFC5BFEF)
val LightInversePrimary = Color(0xFF8794FF)

val DarkPrimary = Color(0xFFABB3FF)
val DarkOnPrimary = Color(0xFF001491)
val DarkPrimaryContainer = Color(0xFF8C98FF)
val DarkOnPrimaryContainer = Color(0xFF000750)
val DarkSecondary = Color(0xFFB8B0FF)
val DarkOnSecondary = Color(0xFF271284)
val DarkSecondaryContainer = Color(0xFF7166D0)
val DarkOnSecondaryContainer = Color(0xFFFFFFFF)
val DarkTertiary = Color(0xFFFF9FDF)
val DarkOnTertiary = Color(0xFF5E024E)
val DarkTertiaryContainer = Color(0xFFF88CD7)
val DarkOnTertiaryContainer = Color(0xFF4C003E)
val DarkError = Color(0xFFFF9DA8)
val DarkOnError = Color(0xFF5F001C)
val DarkErrorContainer = Color(0xFFD73357)
val DarkOnErrorContainer = Color(0xFFFFFFFF)
val DarkSurface = Color(0xFF0D072E)
val DarkBackground = Color(0xFF0D072E)
val DarkOnSurface = Color(0xFFFFFFFF)
val DarkSurfaceVariant = Color(0xFF241D54)
val DarkOnSurfaceVariant = Color(0xFFB9B3E3)
val DarkSurfaceDim = Color(0xFF0D072E)
val DarkSurfaceBright = Color(0xFF2A235E)
val DarkSurfaceContainerLowest = Color(0xFF000000)
val DarkSurfaceContainerLow = Color(0xFF120C37)
val DarkSurfaceContainer = Color(0xFF181241)
val DarkSurfaceContainerHigh = Color(0xFF1E184A)
val DarkSurfaceContainerHighest = Color(0xFF241D54)
val DarkOutline = Color(0xFF938EBC)
val DarkOutlineVariant = Color(0xFF746EAA)
val DarkInverseSurface = Color(0xFFFCF8FF)
val DarkInverseOnSurface = Color(0xFF37335B)
val DarkInversePrimary = Color(0xFF3545C6)
