package dev.gavenda.yuuka.ui.theme

import androidx.compose.ui.graphics.Color

// Material 3 tonal-spot scheme generated from the brand blue (#2A78D6, the launcher
// background). Used when dynamic colour is off or unavailable; regenerate the whole
// set from a new seed rather than editing single roles.
// The surface roles and both backgrounds are tinted towards the primary rather than neutral, so the
// content background, cards and rail read as one hue. The web app mirrors it in `webapp/src/style.css` and `chartInk`; change them together.

val LightPrimary = Color(0xFF005EB4)
val LightOnPrimary = Color(0xFFFFFFFF)
val LightPrimaryContainer = Color(0xFFD5E3FF)
val LightOnPrimaryContainer = Color(0xFF001B3C)
val LightSecondary = Color(0xFF555F71)
val LightOnSecondary = Color(0xFFFFFFFF)
val LightSecondaryContainer = Color(0xFFD9E3F8)
val LightOnSecondaryContainer = Color(0xFF121C2B)
val LightTertiary = Color(0xFF6F5675)
val LightOnTertiary = Color(0xFFFFFFFF)
val LightTertiaryContainer = Color(0xFFF8D8FE)
val LightOnTertiaryContainer = Color(0xFF28132F)
val LightError = Color(0xFFBA1A1A)
val LightOnError = Color(0xFFFFFFFF)
val LightErrorContainer = Color(0xFFFFDAD6)
val LightOnErrorContainer = Color(0xFF410002)
val LightSurface = Color(0xFFF5F8FC)
val LightBackground = Color(0xFFE6EDF7)
val LightOnSurface = Color(0xFF1A1C1E)
val LightSurfaceVariant = Color(0xFFE0E2EC)
val LightOnSurfaceVariant = Color(0xFF43474E)
val LightSurfaceDim = Color(0xFFD6DFEB)
val LightSurfaceBright = Color(0xFFF5F8FC)
val LightSurfaceContainerLowest = Color(0xFFFFFFFF)
val LightSurfaceContainerLow = Color(0xFFF2F5FB)
val LightSurfaceContainer = Color(0xFFE3EBF4)
val LightSurfaceContainerHigh = Color(0xFFD9E3EF)
val LightSurfaceContainerHighest = Color(0xFFCDD9EA)
val LightOutline = Color(0xFF74777F)
val LightOutlineVariant = Color(0xFFBFCAD9)
val LightInverseSurface = Color(0xFF2F3033)
val LightInverseOnSurface = Color(0xFFF1F0F4)
val LightInversePrimary = Color(0xFFA8C8FF)

val DarkPrimary = Color(0xFFA8C8FF)
val DarkOnPrimary = Color(0xFF003062)
val DarkPrimaryContainer = Color(0xFF00468A)
val DarkOnPrimaryContainer = Color(0xFFD5E3FF)
val DarkSecondary = Color(0xFFBDC7DC)
val DarkOnSecondary = Color(0xFF273141)
val DarkSecondaryContainer = Color(0xFF3E4758)
val DarkOnSecondaryContainer = Color(0xFFD9E3F8)
val DarkTertiary = Color(0xFFDBBCE1)
val DarkOnTertiary = Color(0xFF3E2845)
val DarkTertiaryContainer = Color(0xFF563E5D)
val DarkOnTertiaryContainer = Color(0xFFF8D8FE)
val DarkError = Color(0xFFFFB4AB)
val DarkOnError = Color(0xFF690005)
val DarkErrorContainer = Color(0xFF93000A)
val DarkOnErrorContainer = Color(0xFFFFB4AB)
val DarkSurface = Color(0xFF0E121B)
val DarkBackground = Color(0xFF141927)
val DarkOnSurface = Color(0xFFE3E2E6)
val DarkSurfaceVariant = Color(0xFF43474E)
val DarkOnSurfaceVariant = Color(0xFFC4C6CF)
val DarkSurfaceDim = Color(0xFF0E121B)
val DarkSurfaceBright = Color(0xFF3A4460)
val DarkSurfaceContainerLowest = Color(0xFF0A0E16)
val DarkSurfaceContainerLow = Color(0xFF181D2D)
val DarkSurfaceContainer = Color(0xFF1E2438)
val DarkSurfaceContainerHigh = Color(0xFF2A3350)
val DarkSurfaceContainerHighest = Color(0xFF3A4460)
val DarkOutline = Color(0xFF8E9099)
val DarkOutlineVariant = Color(0xFF3A4056)
val DarkInverseSurface = Color(0xFFE3E2E6)
val DarkInverseOnSurface = Color(0xFF2F3033)
val DarkInversePrimary = Color(0xFF005EB4)
